version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope
