export type Capability =
  | "collaborator.create"
  | "collaborator.edit"
  | "collaborator.list"
  | "cycle.coordinator.list"
  | "cycle.management.view"
  | "cycle.team.panel.view"
  | "evaluation.create"
  | "evaluation.edit.manager"
  | "evaluation.edit.coordinator"
  | "evaluation.edit.board"
  | "goal.approve.manager"
  | "goal.approve.coordinator"
  | "observation.create"
  | "observation.edit"
  | "observation.delete"
  | "report.view"
  | "settings.manage";
